scrapers:
  ubc:
    default: &ubc_scrapers
      year: 2018
      years: [2015, 2016, 2017, 2018]
      path: scrapers/ubc/
    scripts:
      excluded.py:
        <<: *ubc_scrapers
        url: http://www.calendar.ubc.ca/vancouver/?tree=12,215,410,414
        outfile: data/ubc/$YEAR/excls.txt
      ubcalend.py:
        <<: *ubc_scrapers
        baseurl: http://www.calendar.ubc.ca/vancouver/
        starturl: http://www.calendar.ubc.ca/vancouver/courses.cfm?page=code
        outfolder: data/ubc/$YEAR/courses/
        logfile: data/ubc/$YEAR/calendar.log
      ubccodes.py:
        <<: *ubc_scrapers
        infile: data/ubc/$YEAR/courses/terms.txt
        outfolder: data/ubc/$YEAR/codes/
      ubcsched.py:
        <<: *ubc_scrapers
        outfile: data/ubc/$YEAR/courses/terms.txt

parsers:
  ubc:
    default: &ubc_parsers
      year: 2018
      years: [2015, 2016, 2017, 2018]
      path: parsers/ubc/
    scripts:
      graph.py:
        <<: *ubc_parsers
      lexer.py:
        <<: *ubc_parsers
      parser.py:
        <<: *ubc_parsers
      main.py:
        <<: *ubc_parsers
      ubcparse.py:
        <<: *ubc_parsers
        infolder: data/ubc/$YEAR/courses/
        exclfile: data/ubc/$YEAR/excls.txt
        outfile: req.json
        exclstr: "This course cannot be taken for credit after having taken any of the following courses: "
